import {useEffect,useState} from 'react';
import {onAuthStateChanged,type User} from 'firebase/auth';
import {collection,doc,getDoc,getDocs,setDoc,deleteDoc,runTransaction,query,where,addDoc,serverTimestamp,onSnapshot} from 'firebase/firestore';
import App from '../App';
import {auth,db,login,logout,installBetaFetch} from './client';
import {refreshTrack} from '../api/catalog';
import type {Like} from '../likes/store';
import {betaLikesStore} from './store';
installBetaFetch();
export function BetaApp(){
 const [user,setUser]=useState<User|null>(null),[allowed,setAllowed]=useState(false),[checking,setChecking]=useState(true),[username,setUsername]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[social,setSocial]=useState(false);
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setAllowed(false);setUsername('');setChecking(true);setError('');if(!u){setChecking(false);return;}void fetch('/api/beta-session').then(async r=>{if(!r.ok)throw Error('This Google account has not been invited.');const p=await getDoc(doc(db,'profiles',u.uid));setUsername(p.exists()?p.data().username:'');setAllowed(true);}).catch(e=>setError(e.message)).finally(()=>setChecking(false));}),[]);
 const claim=async()=>{setError('');try{if(!/^[a-z][a-z0-9_]{2,19}$/.test(name))throw Error('Use 3-20 lowercase letters, numbers or underscores. Start with a letter.');await runTransaction(db,async t=>{const ref=doc(db,'usernames',name);if((await t.get(ref)).exists())throw Error('That username is taken.');t.set(ref,{uid:user!.uid});t.set(doc(db,'memberships',user!.uid),{email:user!.email});t.set(doc(db,'profiles',user!.uid),{username:name,active:true});});setUsername(name);}catch(e){setError((e as Error).message);}};
 if(checking)return <section className="page beta-gate"><p>Checking beta access…</p></section>;
 if(!allowed||!username)return <section className="page beta-gate"><p className="eyebrow">Drift · private beta</p><h1>Your music. Your circle.</h1><p>Invitation-only. Sign in with your invited Google account. Your email is never shown to other testers.</p>{!user?<button className="primary" onClick={()=>void login().catch(e=>setError(e.message))}>Continue with Google</button>:allowed?<><label>Choose your username<input aria-label="Username" value={name} maxLength={20} onChange={e=>setName(e.target.value.toLowerCase())}/></label><p>Usernames cannot be changed in this first beta.</p><button className="primary" onClick={()=>void claim()}>Save username</button></>:null}{user&&<button onClick={()=>void logout()}>Sign out</button>}{error&&<p role="alert">{error}</p>}<p className="muted">Private, free testing. 30-second previews. No contacts access, free-text chat or audio uploads. Likes stay private. Sending a song shares its ID with the person you choose. Approved testers can find each other by username.</p></section>;
 return <><aside className="beta-bar"><span>@{username}</span><button onClick={()=>setSocial(!social)}>{social?'Back to music':'Songs inbox'}</button><button onClick={()=>void logout()}>Sign out</button></aside>{social?<SongsInbox uid={user!.uid}/>:location.pathname==='/download'?<section className="page"><h1>Web beta</h1><p>This private beta runs in your browser. The main-site APK does not include the beta inbox.</p><a href="/">Back to beta</a></section>:<App/>}</>;
}
export function SongsInbox({uid}:{uid:string}){
 const [people,setPeople]=useState<{uid:string;username:string}[]>([]),[likes,setLikes]=useState<Like[]>([]),[messages,setMessages]=useState<any[]>([]),[to,setTo]=useState(''),[song,setSong]=useState(''),[status,setStatus]=useState(''),[resolved,setResolved]=useState<Record<string,{label:string;url?:string;preview?:string}>>({});
 useEffect(()=>{void getDocs(collection(db,'profiles')).then(s=>setPeople(s.docs.filter(d=>d.id!==uid&&d.data().active).map(d=>({uid:d.id,username:d.data().username})))).catch(()=>setStatus('Could not load people.'));void betaLikesStore(uid).list().then(setLikes).catch(()=>setStatus('Could not load saved songs.'));return onSnapshot(query(collection(db,'messages'),where('to','==',uid)),s=>{const m=s.docs.map(d=>({id:d.id,...d.data()})).sort((a:any,b:any)=>(b.sentAt?.seconds||0)-(a.sentAt?.seconds||0));setMessages(m);for(const x of m as any[])void refreshTrack(x.songId).then(t=>setResolved(old=>({...old,[x.id]:{label:`${t.title} · ${t.artist.name}`,url:t.credit?.trackUrl||t.link,preview:t.preview}}))).catch(()=>setResolved(old=>({...old,[x.id]:{label:'Song unavailable in this catalog'}})));},()=>setStatus('Could not load inbox.'));},[uid]);
 const send=async()=>{try{if(!to||!song)throw Error('Choose a person and a saved song.');await addDoc(collection(db,'messages'),{from:uid,to,songId:Number(song),sentAt:serverTimestamp()});setStatus('Song sent.');setSong('');}catch(e){setStatus((e as Error).message);}};
 return <section className="page beta-social"><p className="eyebrow">A small listening circle</p><h1>Songs inbox</h1><p>Only saved songs can be sent. No text, audio files or group chat.</p><label>Send to<select value={to} onChange={e=>setTo(e.target.value)}><option value="">Choose username</option>{people.map(p=><option key={p.uid} value={p.uid}>@{p.username}</option>)}</select></label><label>Saved song<select value={song} onChange={e=>setSong(e.target.value)}><option value="">Choose song</option>{likes.map(l=><option key={l.id} value={l.id}>{l.title} · {l.artistName}</option>)}</select></label><button className="primary" onClick={()=>void send()} disabled={!to||!song}>Send song</button><p role="status">{status}</p><h2>Received</h2>{!messages.length&&<p>No songs received yet.</p>}{messages.map(m=><article className="beta-message" key={m.id}><p>From @{people.find(p=>p.uid===m.from)?.username||'tester'}</p><strong>{resolved[m.id]?.label||'Loading song…'}</strong><p>{resolved[m.id]?.preview&&<audio onPlay={e=>{document.querySelectorAll('audio').forEach(a=>{if(a!==e.currentTarget)a.pause();});}} controls preload="none" src={resolved[m.id].preview} onTimeUpdate={e=>{if(e.currentTarget.currentTime>=30)e.currentTarget.pause();}}/>}</p><p>{resolved[m.id]?.url&&<a href={resolved[m.id].url} target="_blank" rel="noopener noreferrer">Open original song ↗</a>}</p></article>)}</section>;
}
