import {afterEach,it,expect,vi} from 'vitest';
import {nextFeedSeed,recentTracks,rememberTrack} from '../src/feed/freshness';
import {TrackPool} from '../src/feed/pool';
// @ts-expect-error server module
import handler from '../api/catalog.js';
afterEach(()=>{localStorage.clear();vi.unstubAllGlobals();delete process.env.JAMENDO_CLIENT_ID;});
it('rotates refresh windows across reloads without storing audio URLs',()=>{expect(nextFeedSeed()).toBe(0);expect(nextFeedSeed()).toBe(1);rememberTrack(4);rememberTrack(5);rememberTrack(4);expect(recentTracks()).toEqual([5,4]);expect(localStorage.getItem('drift-feed-recent-v1')).toBe('[5,4]');});
it('puts not-recent tracks before repeats while deduplicating pages',()=>{const p=new TrackPool([1]);const t=(id:number)=>({id,title:'Song',artist:{id,name:'A'}});const a=p.append({data:[t(1),t(2),t(2)],next:'more'});expect(a.map(t=>t.id)).toEqual([2,1]);expect(p.exhausted).toBe(false);expect(p.append({data:[t(2),t(3)]}).map(t=>t.id)).toEqual([3]);});
async function call(query:Record<string,string>){let body:any;const res:any={status:vi.fn().mockReturnThis(),setHeader:vi.fn(),json:(b:any)=>body=b};await handler({method:'GET',query},res);return {body,res};}
it('mainstream charts paginate even when provider omits next; refresh uses different IDs',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>({ok:true,json:async()=>({data:Array.from({length:100},(_,i)=>({id:i+1,title:'Song',artist:{id:1,name:'A'}})),total:100})})));const a=await call({source:'deezer',seed:'0',index:'0'});const b=await call({source:'deezer',seed:'1',index:'0'});const c=await call({source:'deezer',seed:'0',index:'25'});expect(a.body.data[0].id).toBe(1);expect(b.body.data[0].id).toBe(26);expect(c.body.data[0].id).toBe(26);expect(a.body.next).toBe('more');expect((await call({source:'deezer',index:'75'})).body.next).toBeUndefined();expect(a.res.setHeader).toHaveBeenCalledWith('Cache-Control','no-store');});
it('Jamendo sends offset for refresh and next page without nonexistent next header',async()=>{process.env.JAMENDO_CLIENT_ID='test';const fetcher=vi.fn(async(_url:string)=>({ok:true,json:async()=>({headers:{status:'success'},results:Array.from({length:100},(_,i)=>({id:String(i+1),artist_id:'1',name:'Song',artist_name:'A',license_ccurl:'https://creativecommons.org/licenses/by/3.0/',shareurl:'https://www.jamendo.com/track/1'}))})}));vi.stubGlobal('fetch',fetcher);const r=await call({source:'jamendo',seed:'2',index:'25'});expect(new URL(fetcher.mock.calls[0][0] as any).searchParams.get('offset')).toBe('225');expect(r.body.next).toBe('more');expect(r.body.routing.served).toBe('jamendo');expect(fetcher).toHaveBeenCalledTimes(1);});
it('rejects bad seeds before hitting providers',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);expect((await call({source:'deezer',seed:'20'})).body.error.message).toBe('Invalid seed');expect(fetcher).not.toHaveBeenCalled();});
