import {useEffect,useState} from 'react';
import {deezer} from '../api/deezer';
import type {Artist} from '../api/types';
import type {Follow} from '../follows/store';
export function Artists({follows,onToggle,onListen}:{follows:Follow[];onToggle:(a:Follow)=>void;onListen:()=>void}) {
 const [query,setQuery]=useState('');const [submitted,setSubmitted]=useState('');const [results,setResults]=useState<Artist[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
 useEffect(()=>{if(!submitted)return;const abort=new AbortController();setLoading(true);setError('');setResults([]);void deezer.artists(submitted,abort.signal).then(r=>{if(!abort.signal.aborted)setResults(r.data.filter(a=>Number.isSafeInteger(a.id)&&a.id>0));}).catch(e=>{if(!abort.signal.aborted)setError('Taking a little longer to find these artists. Try again in a moment.');}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[submitted,retry]);
 const row=(a:Artist|Follow)=>{const followed=follows.some(f=>f.id===a.id);return <div className="artist-row" key={a.id}>{'picture_medium' in a&&a.picture_medium?<img src={a.picture_medium} alt="" referrerPolicy="no-referrer"/>:<span className="artist-avatar">♫</span>}<strong>{a.name}</strong><button aria-label={`${followed?'Unfollow':'Follow'} ${a.name}`} aria-pressed={followed} className={followed?'is-followed':''} onClick={()=>onToggle(a)}>{followed?'Following ✓':'+ Follow'}</button></div>;};
 return <section className="page artists"><p className="eyebrow">Make it your music</p><h1>Follow your artists.</h1><p>Search Telugu, Hindi or any artist. Your Following feed plays their available previews.</p><form onSubmit={e=>{e.preventDefault();if(query.trim()){setSubmitted(query.trim());setRetry(r=>r+1);}}}><label htmlFor="artist-search">Search artists</label><div className="artist-search"><input id="artist-search" value={query} maxLength={200} onChange={e=>setQuery(e.target.value)} placeholder="Sid Sriram, Anirudh…"/><button type="submit" className="primary" disabled={!query.trim()}>Search</button></div></form><div className="artist-seeds">{['Sid Sriram','Anirudh Ravichander','Devi Sri Prasad','A. R. Rahman'].map(name=><button key={name} onClick={()=>{setQuery(name);setSubmitted(name);setRetry(r=>r+1);}}>{name}</button>)}</div>{submitted&&<><h2>Search results</h2>{loading?<p role="status">Finding artists…</p>:error?<div role="alert"><p>{error}</p><button onClick={()=>setRetry(r=>r+1)}>Retry search</button></div>:results.length?results.map(row):<p>No artists found. Try a different spelling.</p>}</>}<div className="section-heading"><h2>Your artists <small>{follows.length}</small></h2>{!!follows.length&&<button onClick={onListen}>Listen ↗</button>}</div>{follows.length?follows.map(row):<p>No artists followed yet. Search above and tap Follow.</p>}<p className="muted">Saved on this device. No account needed. Availability varies by artist and region.</p></section>;
}
