import {useEffect,useRef,useState} from 'react';
import type {Track} from '../api/types';import {apiUrl} from '../api/base';
type Result={text:string;sourceUrl:string;syncedAvailable:boolean;syncedLyrics?:string;source?:string};
export function parseLrc(raw:string){const lines:{time:number;text:string}[]=[];let offset=0;const match=raw.match(/\[offset:([+-]?\d+)\]/i);if(match)offset=Number(match[1])/1000;for(const line of raw.split('\n')){const tags=[...line.matchAll(/\[(\d{1,3}):(\d{2})(?:\.(\d{1,3}))?\]/g)];const text=line.replace(/\[[^\]]*\]/g,'').trim();for(const m of tags){const time=Number(m[1])*60+Number(m[2])+Number('0.'+(m[3]||'0'))+offset;if(Number(m[2])<60&&time>=0&&text)lines.push({time,text});}}return lines.sort((a,b)=>a.time-b.time);}
export function Lyrics({track,progress=0}:{track:Track;progress?:number}){
 const [open,setOpen]=useState(false),[lyrics,setLyrics]=useState<Result|null>(null),[status,setStatus]=useState('');const current=useRef<HTMLParagraphElement>(null);
 useEffect(()=>{setOpen(false);setLyrics(null);setStatus('');},[track.id]);
 useEffect(()=>{if(!open)return;let valid=true;const abort=new AbortController();const fallback=track.source==='jamendo'&&track.lyrics?{text:track.lyrics,source:'Jamendo',sourceUrl:track.credit?.trackUrl||'https://www.jamendo.com/',syncedAvailable:false}:null;setLyrics(fallback);setStatus(fallback?'Checking synced lyrics…':'Checking lyrics…');
 const query=new URLSearchParams({title:track.title,artist:track.artist.name,album:track.album?.title||'',...(track.duration?{duration:String(track.duration)}:{})});
 fetch(apiUrl('/api/lyrics?'+query),{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>{if(valid){const result=track.source==='jamendo'&&d.lyrics?.syncedAvailable?d.lyrics:fallback||d.lyrics;setLyrics(result);setStatus(result?'':'No matching lyrics available.');}}).catch(()=>{if(valid)setStatus(fallback?'':'Lyrics unavailable right now.');});return()=>{valid=false;abort.abort();};},[open,track.id]);
 const lines=track.source==='jamendo'&&lyrics?.syncedAvailable&&lyrics.syncedLyrics?parseLrc(lyrics.syncedLyrics):[];const active=lines.reduce((found,l,i)=>l.time<=progress?i:found,-1);
 useEffect(()=>{if(open&&lines.length)current.current?.scrollIntoView({block:'center',behavior:'smooth'});},[active,open]);
 return <div className="lyrics-control"><button onClick={()=>setOpen(v=>!v)} aria-expanded={open}>Lyrics {open?'−':'+'}</button>{open&&<div className="lyrics-sheet"><div className="lyrics-heading"><strong>{lines.length?'Synced lyrics':'Lyrics'}</strong><button aria-label="Close lyrics" onClick={()=>setOpen(false)}>×</button></div>{lyrics?<><p className="lyrics-note">{lines.length?'Line-synced to Jamendo audio during the 30-second preview. Community timing may contain errors.':track.source==='jamendo'?'Static lyrics. Matching timed lyrics are not available.':"Static lyrics. This preview's full-song position is unknown, so lyrics are not synced."}</p>{lines.length?<div className="karaoke-lines">{active<0&&<p className="lyrics-note">{lines[0]?.time>=30?'Vocals begin after this 30-second preview. No lyric line is active in this clip.':'Instrumental intro. Lyrics will highlight when vocals begin.'}</p>}{lines.map((l,i)=><p key={i} ref={i===active?current:undefined} className={i===active?'current-line':''} aria-current={i===active?'true':undefined}>{l.text}</p>)}</div>:<pre>{lyrics.text}</pre>}<a href={lyrics.sourceUrl} target="_blank" rel="noopener noreferrer">Lyrics via {lyrics.source||'LRCLIB'} ↗</a>{track.source==='jamendo'&&track.credit&&<a href={track.credit.licenseUrl} target="_blank" rel="noopener noreferrer">Track license ↗</a>}<p className="lyrics-note">Lyrics may contain errors. Rights and license terms remain with their owners.</p></>:<p role="status">{status||'Checking lyrics…'}</p>}</div>}</div>;
}
