import {useEffect,useRef,useState} from 'react';
import type {Track} from '../api/types';import {playable} from '../api/types';import type {AudioState} from '../audio/controller';import {ListenLinks} from './ListenLinks';import {Lyrics} from './Lyrics';import {StitchIcon} from './StitchIcon';
type Props={track:Track;index:number;active:boolean;liked:boolean;state:AudioState;onActive:(i:number)=>void;onLike:()=>void;onPlay:()=>void;onPause:()=>void;onRetry:()=>void;onNext:()=>void;onHighlight:()=>void;onFromStart:()=>void;followed?:boolean;onFollow?:()=>void;onTune?:()=>void;tags?:string[]};
export function SongCard({track,index,active,liked,state,onActive,onLike,onPlay,onPause,onRetry,onNext,onHighlight,onFromStart,followed,onFollow,onTune,tags=[]}:Props){
 const ref=useRef<HTMLElement>(null),[imageError,setImageError]=useState(false),[sharing,setSharing]=useState('');useEffect(()=>{const o=new IntersectionObserver(e=>{if(e.some(v=>v.isIntersecting&&v.intersectionRatio>=.75))onActive(index);},{threshold:[0,.75,1]});if(ref.current)o.observe(ref.current);return()=>o.disconnect();},[index,onActive]);
 const art=track.album?.cover_xl||track.album?.cover_big;const time=active?Math.floor(state.progress):0;const share=async()=>{try{const url=track.credit?.trackUrl||track.link;if(!url){setSharing('Use Listen full for platform links.');return;}if(navigator.share)await navigator.share({title:track.title,text:track.title+' · '+track.artist.name,url});else{await navigator.clipboard.writeText(url);setSharing('Track link copied.');}}catch{setSharing('Sharing canceled or unavailable.');}};
 return <article ref={ref} className="song-card stitch-reel" data-index={index} aria-label={`${track.title} by ${track.artist.name}`}>
 <div className="absolute inset-0 z-0">{art&&!imageError?<img src={art} alt={`${track.album?.title||track.title} album artwork`} className="w-full h-full object-cover object-center scale-[1.03] select-none pointer-events-none" onError={()=>setImageError(true)} loading={active?'eager':'lazy'} referrerPolicy="no-referrer"/>:<div className="stitch-fallback">♫</div>}<div className="absolute inset-0 bg-gradient-to-b from-[#08080A]/85 via-transparent to-[#08080A]/95 mix-blend-multiply"/><div className="absolute inset-0 bg-gradient-to-t from-[#08080A] via-[#08080A]/50 to-transparent"/></div>
 <div className="stitch-workspace relative z-10 flex-1 flex flex-col justify-end pb-3">
 <aside className="absolute right-4 bottom-24 flex flex-col items-center space-y-4" data-purpose="reel-actions">
 <div className="relative mb-1"><button onClick={onFollow||onTune} aria-label={onFollow?(followed?'Unfollow artist':'Follow artist'):'Discover preferences'} aria-pressed={followed} className="stitch-avatar w-11 h-11 rounded-full p-[1.5px] bg-gradient-to-tr from-brand-lime to-white/20">{art&&!imageError?<img alt="Track artwork" className="w-full h-full rounded-full object-cover" src={art}/>:<span>♫</span>}<span className="stitch-follow-badge">{followed?'✓':'+'}</span></button></div>
 <button aria-label={liked?'Unlike song':'Like song'} aria-pressed={liked} onClick={onLike} className="flex flex-col items-center group"><div className={`w-11 h-11 rounded-full glass-btn flex items-center justify-center ${liked?'text-brand-lime':'text-white/90'}`}><StitchIcon name="heart"/></div><span className="text-[11px] font-semibold text-white/80 mt-1">{liked?'Saved':'Like'}</span></button>
 <button aria-label="Discover preferences" onClick={onTune} className="flex flex-col items-center group"><div className="w-11 h-11 rounded-full glass-btn flex items-center justify-center text-white/90"><StitchIcon name="tune"/></div><span className="text-[11px] font-medium text-white/70 mt-1">Tune</span></button>
 <button aria-label="Share song" onClick={()=>void share()} className="flex flex-col items-center group"><div className="w-11 h-11 rounded-full glass-btn flex items-center justify-center text-white/90"><StitchIcon name="share"/></div><span className="text-[11px] font-medium text-white/70 mt-1">Share</span></button>
 </aside>
 <div className="self-center mb-8 pointer-events-auto" data-purpose="playback-control"><button aria-label={active&&state.playing?'Pause preview':active&&state.ended?'Replay preview':'Play preview'} onClick={active&&state.playing?onPause:onPlay} disabled={!playable(track)} className="relative w-14 h-14 rounded-full glass-btn flex items-center justify-center border border-white/20">{active&&state.playing?<span className="text-brand-lime">Ⅱ</span>:<StitchIcon name="play"/>}</button></div>
 <section aria-label="Track Information" className="px-5 pr-20"><div className="flex items-center space-x-2 mb-2.5">{tags.slice(0,2).map(t=><span key={t} className="glass-pill px-3 py-1 rounded-full text-[11px] font-semibold tracking-wider uppercase text-white/90">{t}</span>)}<span className="glass-pill px-2.5 py-1 rounded-full text-[10px] text-white/60 tracking-wider">30s Clip</span></div><h1 className="text-[28px] font-bold tracking-tight text-white leading-tight font-display drop-shadow-md">{track.title}</h1><div className="flex items-center space-x-2 mt-1 stitch-artist"><span className="text-base font-semibold text-white/90 tracking-wide">{track.artist.name}</span>{track.explicit_lyrics&&<span className="explicit">E</span>}<span className="text-white/40 text-xs">•</span><span className="text-xs text-white/60 font-normal">{track.album?.title}</span></div><ListenLinks track={track}/><Lyrics track={track} progress={active?state.progress:0}/>{track.source==='jamendo'&&track.credit&&<div className="source credit"><span>{track.credit.artist} · Jamendo</span><a href={track.credit.trackUrl} target="_blank" rel="noopener noreferrer">Track ↗</a><a href={track.credit.licenseUrl} target="_blank" rel="noopener noreferrer">CC ↗</a></div>}</section>
 <div className="px-5 mt-4" data-purpose="audio-scrubber"><div className="progress relative w-full h-[4px] bg-white/15 rounded-full" role="progressbar" aria-label="Preview progress" aria-valuenow={time} aria-valuemin={0} aria-valuemax={30}><span className="h-full bg-brand-lime rounded-full relative" style={{width:active?`${Math.min(100,100*state.progress/state.duration)}%`:'0%'}}><i className="stitch-thumb"/></span></div><div className="flex justify-between items-center text-[10px] font-mono tracking-wider text-white/50 mt-1.5"><span className="text-brand-lime font-medium">0:{String(time).padStart(2,'0')}</span><span>0:30</span></div></div>
 <div className="stitch-extra"><span role="status">{sharing||(!playable(track)?'No playable preview.':active?state.message:'')}</span>{active&&state.message.includes('unavailable')&&<button onClick={onRetry}>Retry</button>}<button onClick={onNext} aria-label="Next song">Next ↑</button>{active&&state.highlight&&<><button onClick={onHighlight}>Highlight ↗</button><button onClick={onFromStart}>From start</button></>}</div>
 </div></article>;
}
